name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Decrypting keys
        if: github.ref == 'refs/heads/master'
        run: | 
          echo "Creating ssh"
          mkdir ~/.ssh
          chmod 755 ~/.ssh
          echo "Decrypting wollok-cli"
          openssl aes-128-ctr -d -K ${{ secrets.WOLLOK_CLI_KEY }} -iv ${{ secrets.WOLLOK_CLI_IV }} -in ./scripts/wollokcli_key.enc -out ~/.ssh/wollokcli_key
          echo "Decrypting wollok-site"
          openssl aes-128-ctr -d -K ${{ secrets.WOLLOK_SITE_KEY }} -iv ${{ secrets.WOLLOK_SITE_IV }} -in ./scripts/wolloksite_key.enc -out ~/.ssh/wolloksite_key
          chmod 600 ~/.ssh/wollokcli_key ~/.ssh/wolloksite_key
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_JOB: $GITHUB_JOB
      - name: Run Maven Build
        run: | 
          openssl aes-256-cbc -pass pass:${{ secrets.SETTINGS_GPG_TOKEN }} -pbkdf2 -in ./settings.xml.enc -out ./settings.xml -d
          mv ./settings.xml ~/.m2/settings.xml
          export DISPLAY=:99.0
          sudo apt-get install -y xvfb
          ./wollokInstall.sh
          cd org.uqbar.project.wollok.releng/
          export PROFILES=normalProfile
          export UPDATE_SITE=none
          echo "Running with profiles $PROFILES"
          echo "Running with UPDATE_SITE $UPDATE_SITE"
          export MAVEN_OPTS=-Xmx2048m
          mvn -q -N io.takari:maven:0.7.7:wrapper -Dmaven=3.5.0 && xvfb-run ./mvnw -V -e -Darguments='-Dtycho.disableP2Mirrors=false' \
           -D tycho.disableP2Mirrors=false -U \
           -D repoToken=${{ secrets.GITHUB_TOKEN }} \
           clean install jacoco:report \
           coveralls:report \
           -P $PROFILES
          cd ..
        env:
          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CI_NAME: github
          BRANCH_NAME_OR_REF: ${{ github.head_ref || github.ref }}
          CI_BUILD_NUMBER: ${{ github.run_id }}
          CI_BUILD_URL: https://github.com/${{ github.repository }}/commit/${{ github.event.after }}/checks
          CI_PULL_REQUEST: ${{ steps.refs.outputs.pr_number }}
      - name: Updating wollok-cli & wollok-site
        if: github.ref == 'refs/heads/master'
        run: | 
          cd ./scripts
          cp ./ssh_config ~/.ssh/config
          chmod 777 ./updateRestOfWollokRepos.sh
          "./updateRestOfWollokRepos.sh"
          cd ..
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_RUN_ID: $GITHUB_RUN_ID
      - name: Releasing Latest Development Version
        if: github.ref == 'refs/heads/dev'
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            **/wollok-linux*64.zip
            **/wollok-macosx*64.zip
            **/wollok-win32*64.zip
      - name: Product Release
        uses: "marvinpinto/action-automatic-releases@latest"
        if: startsWith(github.ref, 'refs/tags/')
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false          
          files: |
            **/wollok-linux*64.zip
            **/wollok-macosx*64.zip
            **/wollok-win32*64.zip
